spring :
   datasource :
      hikari :
         driver-class-name : com.mysql.cj.jdbc.Driver
         jdbc-url : jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
         username : root
         password : 1234
         connection-test-query : "SELECT 1"
   mvc :
      throw-exception-if-no-handler-found : true
   resources :
      add-mappings : false
   
mybatis :
   configuration :
      map-underscore-to-camel-case : true
 
logging : 
   level :
       web : INFO